paths:
  raw_data: "marked_data"
  processed_data: "processed_data"
  yolo_datasets: "yolo_datasets"
  models: "trained_models"
  cache: "cache"

data:
  image_size: [1690, 4660]
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  random_seed: 42

models:
  shoe_segmentation:
    model_size: "yolov8m-seg"
    epochs: 100
    batch_size: 8
    imgsz: 640
    confidence: 0.5

  axis_detection:
    model_size: "yolov8m"
    epochs: 100
    batch_size: 16
    imgsz: 640
    confidence: 0.5

  feature_detection:
    model_size: "yolov8m"
    epochs: 150
    batch_size: 16
    imgsz: 640
    confidence: 0.10
  use_sahi: true

matching:
  dtw:
    window_size: 1
    distance_threshold: 0.1
    use_segmentation: true
  features:
    iou_threshold: 0.05
    min_matches: 3
  weights:
    feature_weight: 0.2
    dtw_weight: 0.8
